%% HEADER INFORMATION
%By: QuocBao Vu
%Created: Dec. 31, 2012
%Modified: Dec. 31, 2012
%Version: 1
%
%This script reslices dicom image stack automatical by reading a log file
%outputted from the DicomViewer program. The file can also be generated by
%hand if needed. This first creates a Dicom3D objects from the files in the
%input directory and then reads in the log file and the commands. The
%program executes the commands automatically. The only step that need
%to be done manuall is when changing the pixel spacing since the user has
%to crop out the desired area. Once all the commands are executed from the
%log the files will be writen out to the output directory

%% EXECUTION CODE
clear all
close all
clc

%Set the input directory, output directory and log file to execute command
%from
inputDirectory = 'D:\DFSS\cd003\InputDicom\';
outputDirectory = 'Test';
logFile = 'DicomViewerCommandlog.txt';

%Read the commands to execute from the log file. A java scanner is used
%here
javaFile = java.io.File(logFile);
javaQ = java.util.LinkedList();
javaScanner = java.util.Scanner(javaFile);

while (javaScanner.hasNext())
    if (javaScanner.hasNextDouble)
        command = javaScanner.nextDouble();
    else
        command = javaScanner.next();
    end
    
    javaQ.add(command);
end

%Initialize the Dicom Stack object
imageStack = Dicom3D(inputDirectory);

%Run the commands
while (~javaQ.isEmpty())
    command = javaQ.remove();
    if (strcmpi(command, 'CPS'))
        pixelSpacing = javaQ.remove();
        imageStack.changePixelSpacing(pixelSpacing);
    elseif (strcmpi(command, 'Compress'))
        newSliceSpacing = javaQ.remove();
        imageStack.compress(newSliceSpacing);
    elseif (strcmpi(command, 'ISO'));
        imageStack.makeIsometric();
    elseif (strcmpi(command, 'upR'))
        imageStack.rotateUp();
    elseif (strcmpi(command, 'downR'))
        imageStack.rotateDown();
    elseif (strcmpi(command, 'leftR'))
        imageStack.rotateLeft();
    elseif (strcmpi(command, 'rightR'))
        imageStack.rotateRight();
    elseif (strcmpi(command, 'ccwR'))
        imageStack.rotateCCW();
    elseif (strcmpi(command, 'cwR'))
        imageStack.rotateCW();
    elseif (strcmpi(command, 'Invert'))
        imageStack.invert();
    end
end

%Write the image
if (~exist(outputDirectory, 'dir'))
    mkdir(outputDirectory);
end
imageStack.write(outputDirectory);

%% END PROGRAM