%By: QuocBao Vu
%Created: Dec. 20th, 2012
%Last Modifed; Dec. 20th, 2012
%Version: 1
%
%This class is the view for the dicom reslicing program. It updates the
%information like pixel spacing, slice spacing, slice number and the image
%that is display for both the main components and sec components. This
%updates occur when the user press a control that modifies the model in
%turn updating what the view displays


classdef DicomViewerView < handle
    %DICOMVIEWERVIEW Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        model;              %The model
        
        displayMain;        %Main display
        displaySec;         %Secondary display
        
        dirDisplayMain;     %Main dirctory text box
        dirDisplaySec;      %Secondaru directory text box
        
        infoPanelMain;      %Main info panel
        infoPanelSec;       %Secondary info panel
        imageNumberMain;    %Current image number on the main side
        pixelSpacingMain;   %Current pixel spacing on the main side
        sliceSpacingMain;   %Current slice spacing on the main side
        imageNumberSec;     %Current image number onf the secondary side
        pixelSpacingSec;    %Current pixel spacing on the secondary side
        sliceSpacingSec;    %Current slice spacing on the secondary side
    end
    
    methods
        %post: Add the input model to the view
        function this = DicomViewerView(model)
            this.model = model;
        end
        
        %post: Add the two display to the main window in the controller
        function addDisplay(this, parent)
            %Main Axes
            this.displayMain = axes(...
                'parent', parent, ...
                'units', 'pixels', ...
                'position', [15 285 512 512], ...
                'xlim', [0 512], ...
                'ylim', [0 512], ...
                'visible', 'off');
            %Secondary Axes
            this.displaySec = axes(...
                'parent', parent, ...
                'units', 'pixel', ...
                'position', [805 285 512 512], ...
                'xlim', [0 512], ...
                'ylim', [0 512], ...
                'visible', 'off');
        end
        
        %post: Add the directory text box to the directory panel for the
        %      main and sec components
        function addDirTextBox(this, mainP, secP)
            this.dirDisplayMain = uicontrol(...
                'style', 'text', ...
                'parent', mainP, ...
                'units', 'normalized', ...
                'position', [.05 .5 .9 .35], ...
                'backgroundcolor', [1 1 1]);
            this.dirDisplaySec = uicontrol(...
                'style', 'text', ...
                'parent', secP,...
                'units', 'normalized', ...
                'position', [.05 .5 .9 .35], ...
                'backgroundcolor', [1 1 1]);
            
        end
        
        %post: Add the components that display the info on pixel spacing,
        %      slice spacing, and slice number for both main and secondary
        function addInfoDisplay(this, parent)
            %Main
            this.infoPanelMain = uipanel(...
                'parent', parent, ...
                'units', 'pixel', ...
                'position', [555 550, 240, 70]);
            this.imageNumberMain  = uicontrol(...
                'style', 'text', ...
                'parent', this.infoPanelMain , ...
                'units', 'normalized', ...
                'position', [.05 .65 .9 .25], ...
                'fontweight', 'bold', ...
                'fontsize', 9, ...
                'string', 'NaN');
            this.pixelSpacingMain  = uicontrol(...
                'style', 'text', ...
                'parent', this.infoPanelMain , ...
                'units', 'normalized', ...
                'position', [.05 .375 .9 .25], ...
                'fontweight', 'bold', ...
                'fontsize', 9, ...
                'string', 'Pixel Spacing = NaN');
            this.sliceSpacingMain = uicontrol(...
                'style', 'text', ...
                'parent', this.infoPanelMain , ...
                'units', 'normalized', ...
                'position', [.05 .1 .9 .25], ...
                'fontweight', 'bold', ...
                'fontsize', 9, ...
                'string', 'Slice Spacing = NaN');
            %Secondary
            this.infoPanelSec = uipanel(...
                'parent', parent, ...
                'units', 'pixel', ...
                'position', [1345 550, 240, 70]);
            this.imageNumberSec  = uicontrol(...
                'style', 'text', ...
                'parent', this.infoPanelSec, ...
                'units', 'normalized', ...
                'position', [.05 .65 .9 .25], ...
                'fontweight', 'bold', ...
                'fontsize', 9, ...
                'string', 'NaN');
            this.pixelSpacingSec  = uicontrol(...
                'style', 'text', ...
                'parent', this.infoPanelSec, ...
                'units', 'normalized', ...
                'position', [.05 .375 .9 .25], ...
                'fontweight', 'bold', ...
                'fontsize', 9, ...
                'string', 'Pixel Spacing = NaN');
            this.sliceSpacingSec = uicontrol(...
                'style', 'text', ...
                'parent', this.infoPanelSec, ...
                'units', 'normalized', ...
                'position', [.05 .1 .9 .25], ...
                'fontweight', 'bold', ...
                'fontsize', 9, ...
                'string', 'Slice Spacing = NaN');
            
        end
        
        %post: Update the dir text box and pixel/slice spacing for the main
        %      side
        function updateMain(this)
            mainDir = this.model.getMainDirectory;
            
            set(this.dirDisplayMain, 'string', mainDir);
            
            set(this.pixelSpacingMain, 'string', ...
                ['Pixel Spacing = ' ...
                num2str(this.model.getMainPixelSpacing())]);
            set(this.sliceSpacingMain, 'string', ...
                ['Slice Spacing = ' ...
                num2str(this.model.getMainSliceSpacing())]);
        end
        
        %post: Update the dir text box and pixel/slice spacing for the
        %      seconary side
        function updateSec(this)
            secDir = this.model.getSecDirectory;
            set(this.dirDisplaySec, 'string', secDir);
            
            set(this.pixelSpacingSec, 'string', ...
                ['Pixel Spacing = ' ...
                num2str(this.model.getSecPixelSpacing())]);
            set(this.sliceSpacingSec, 'string', ...
                ['Slice Spacing = ' ...
                num2str(this.model.getSecSliceSpacing())]);
        end
            
        %post: Update the the main axes and slice number display
        function updateMainDisplay(this)
            if (strcmpi(get(this.displayMain, 'visible'), 'off'))
                set(this.displayMain, 'visible', 'on');
            end
            set(this.imageNumberMain, 'string', ...
                num2str(this.model.getMainImageNumber()));
            axes(this.displayMain);
            imshow(this.model.getSliceMain(), ...
                [this.model.getMainContrastMin(), ...
                this.model.getMainContrastMax()]);
        end
        
        %post: Update the dir secondary axes and slice number display
        function updateSecDisplay(this)
            if (strcmpi(get(this.displaySec, 'visible'), 'off'))
                set(this.displaySec, 'visible', 'on');
            end
            set(this.imageNumberSec, 'string', ...
                num2str(this.model.getSecImageNumber()));
            axes(this.displaySec);
            imshow(this.model.getSliceSec(), ...
                [this.model.getSecContrastMin(), ...
                this.model.getSecContrastMax()]);
        end      
    end    
end

